"""empty message

Revision ID: 36b668aeb74b
Revises: b21fbe4fe8d
Create Date: 2014-09-08 16:56:54.606344

"""

# revision identifiers, used by Alembic.
revision = '36b668aeb74b'
down_revision = 'b21fbe4fe8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('option3', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'option3')
    ### end Alembic commands ###
