"""empty message

Revision ID: 3bfa652d7d44
Revises: 1d79416c8f8c
Create Date: 2014-08-30 19:24:39.921807

"""

# revision identifiers, used by Alembic.
revision = '3bfa652d7d44'
down_revision = '1d79416c8f8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
