"""empty message

Revision ID: 3dde19f4ae34
Revises: 192e173e89cd
Create Date: 2014-08-27 06:35:38.532940

"""

# revision identifiers, used by Alembic.
revision = '3dde19f4ae34'
down_revision = '192e173e89cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_id', sa.Text(), nullable=True))
    op.drop_column('posts', u'pos_product_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column(u'pos_product_id', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'post_id')
    ### end Alembic commands ###
