"""add pos_product_id to variant

Revision ID: 499185bcd720
Revises: a5294afcae9
Create Date: 2014-09-09 08:53:41.013041

"""

# revision identifiers, used by Alembic.
revision = '499185bcd720'
down_revision = 'a5294afcae9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('pos_product_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variants', 'pos_product_id')
    ### end Alembic commands ###
