"""empty message

Revision ID: 4ffc981e8ac8
Revises: 51f5ccfba190
Create Date: 2014-08-15 14:28:51.358670

"""

# revision identifiers, used by Alembic.
revision = '4ffc981e8ac8'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('productName', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('sales', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sales')
    op.drop_column('posts', 'productName')
    op.drop_column('posts', 'price')
    ### end Alembic commands ###
