"""barcode sku and title added to comment

Revision ID: 51797465c45a
Revises: 4821e8095cb3
Create Date: 2014-08-26 07:23:07.979986

"""

# revision identifiers, used by Alembic.
revision = '51797465c45a'
down_revision = '4821e8095cb3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('barcode', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('sku', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    op.drop_column('comments', 'sku')
    op.drop_column('comments', 'barcode')
    ### end Alembic commands ###
