"""added collection class

Revision ID: 589e155746cf
Revises: 3511e3ab31d9
Create Date: 2014-09-13 07:30:08.638095

"""

# revision identifiers, used by Alembic.
revision = '589e155746cf'
down_revision = '3511e3ab31d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_dept_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_collections')
    ### end Alembic commands ###
