"""added product table

Revision ID: 700432756f7
Revises: 192e173e89cd
Create Date: 2014-08-27 09:08:29.697048

"""

# revision identifiers, used by Alembic.
revision = '700432756f7'
down_revision = '192e173e89cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('productName', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'product_id')
    )
    op.create_index('ix_product_timestamp', 'product', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column(u'post_id', sa.TEXT(), nullable=True))
    op.add_column(u'comments', sa.Column(u'post_id', sa.INTEGER(), nullable=True))
    op.drop_index('ix_product_timestamp', 'product')
    op.drop_table('product')
    ### end Alembic commands ###
