"""adding option 3

Revision ID: a5294afcae9
Revises: 36b668aeb74b
Create Date: 2014-09-09 08:15:08.644847

"""

# revision identifiers, used by Alembic.
revision = 'a5294afcae9'
down_revision = '36b668aeb74b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
