"""empty message

Revision ID: b21fbe4fe8d
Revises: 3b9b6851edea
Create Date: 2014-09-08 16:43:57.325758

"""

# revision identifiers, used by Alembic.
revision = 'b21fbe4fe8d'
down_revision = '3b9b6851edea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variants', sa.Column('compare_at_price', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('variants', sa.Column('fulfillment_service', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('grams', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('inventory_management', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('inventory_policy', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('inventory_quantity', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('option1', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('option2', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('variants', sa.Column('price', sa.Text(), nullable=True))
    op.add_column('variants', sa.Column('requires_shipping', sa.Boolean(), nullable=True))
    op.add_column('variants', sa.Column('taxable', sa.Boolean(), nullable=True))
    op.add_column('variants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('variants', u'timestamp')
    op.drop_column('variants', u'barcode')
    op.drop_column('variants', u'pos_product_id')
    #op.drop_index('ix_variants_timestamp', 'variants')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_variants_timestamp', 'variants', [u'timestamp'], unique=False)
    op.add_column('variants', sa.Column(u'pos_product_id', sa.INTEGER(), nullable=True))
    op.add_column('variants', sa.Column(u'barcode', sa.TEXT(), nullable=True))
    op.add_column('variants', sa.Column(u'timestamp', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('variants', 'updated_at')
    op.drop_column('variants', 'taxable')
    op.drop_column('variants', 'requires_shipping')
    op.drop_column('variants', 'price')
    op.drop_column('variants', 'position')
    op.drop_column('variants', 'option2')
    op.drop_column('variants', 'option1')
    op.drop_column('variants', 'inventory_quantity')
    op.drop_column('variants', 'inventory_policy')
    op.drop_column('variants', 'inventory_management')
    op.drop_column('variants', 'grams')
    op.drop_column('variants', 'fulfillment_service')
    op.drop_column('variants', 'created_at')
    op.drop_column('variants', 'compare_at_price')
    ### end Alembic commands ###
