"""empty message

Revision ID: 192e173e89cd
Revises: 51797465c45a
Create Date: 2014-08-26 20:00:44.894993

"""

# revision identifiers, used by Alembic.
revision = '192e173e89cd'
down_revision = '51797465c45a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('pos_product_id', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'pos_product_id')
    ### end Alembic commands ###
